require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FireteamsController do

  # This should return the minimal set of attributes required to create a valid
  # Fireteam. As you add validations to Fireteam, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FireteamsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fireteams as @fireteams" do
      fireteam = Fireteam.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fireteams).should eq([fireteam])
    end
  end

  describe "GET show" do
    it "assigns the requested fireteam as @fireteam" do
      fireteam = Fireteam.create! valid_attributes
      get :show, {:id => fireteam.to_param}, valid_session
      assigns(:fireteam).should eq(fireteam)
    end
  end

  describe "GET new" do
    it "assigns a new fireteam as @fireteam" do
      get :new, {}, valid_session
      assigns(:fireteam).should be_a_new(Fireteam)
    end
  end

  describe "GET edit" do
    it "assigns the requested fireteam as @fireteam" do
      fireteam = Fireteam.create! valid_attributes
      get :edit, {:id => fireteam.to_param}, valid_session
      assigns(:fireteam).should eq(fireteam)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fireteam" do
        expect {
          post :create, {:fireteam => valid_attributes}, valid_session
        }.to change(Fireteam, :count).by(1)
      end

      it "assigns a newly created fireteam as @fireteam" do
        post :create, {:fireteam => valid_attributes}, valid_session
        assigns(:fireteam).should be_a(Fireteam)
        assigns(:fireteam).should be_persisted
      end

      it "redirects to the created fireteam" do
        post :create, {:fireteam => valid_attributes}, valid_session
        response.should redirect_to(Fireteam.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fireteam as @fireteam" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fireteam.any_instance.stub(:save).and_return(false)
        post :create, {:fireteam => {}}, valid_session
        assigns(:fireteam).should be_a_new(Fireteam)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fireteam.any_instance.stub(:save).and_return(false)
        post :create, {:fireteam => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fireteam" do
        fireteam = Fireteam.create! valid_attributes
        # Assuming there are no other fireteams in the database, this
        # specifies that the Fireteam created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fireteam.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => fireteam.to_param, :fireteam => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested fireteam as @fireteam" do
        fireteam = Fireteam.create! valid_attributes
        put :update, {:id => fireteam.to_param, :fireteam => valid_attributes}, valid_session
        assigns(:fireteam).should eq(fireteam)
      end

      it "redirects to the fireteam" do
        fireteam = Fireteam.create! valid_attributes
        put :update, {:id => fireteam.to_param, :fireteam => valid_attributes}, valid_session
        response.should redirect_to(fireteam)
      end
    end

    describe "with invalid params" do
      it "assigns the fireteam as @fireteam" do
        fireteam = Fireteam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fireteam.any_instance.stub(:save).and_return(false)
        put :update, {:id => fireteam.to_param, :fireteam => {}}, valid_session
        assigns(:fireteam).should eq(fireteam)
      end

      it "re-renders the 'edit' template" do
        fireteam = Fireteam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fireteam.any_instance.stub(:save).and_return(false)
        put :update, {:id => fireteam.to_param, :fireteam => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fireteam" do
      fireteam = Fireteam.create! valid_attributes
      expect {
        delete :destroy, {:id => fireteam.to_param}, valid_session
      }.to change(Fireteam, :count).by(-1)
    end

    it "redirects to the fireteams list" do
      fireteam = Fireteam.create! valid_attributes
      delete :destroy, {:id => fireteam.to_param}, valid_session
      response.should redirect_to(fireteams_url)
    end
  end

end
